#!/usr/bin/python -tt
"""Python script to start sfuzz with basic configuration and use the fuzzing payload generated by it for fuzzing
openstack services using curl command"""
import subprocess
import os
import json
import sys
print sys.argv
token = ""
sfuzzconfig = "/home/test/sfuzz/pythonscript/sfuzzconfig"
#Function to get token from keystone and store it in jsonoutput.txt
def get_token():
		print "\nGetting token from keystone\n"
		#password = raw_input("Enter authentication password for getting keystone token : ")
		password="password"
		subprocess.call(['./tokengen.sh',password])

"""#Function to call api with the Fuzz payload
def api_call(api): 
	print token       
	file_object1 = open("fuzzload1", "r")
        i =1
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                api = "./" + api
                print "Printing token"
		print token
                subprocess.call([api, line, token])
                i +=1
	print "\n\nEnd of one API FUZZ test\n\n"
"""
#Function to parse the json output in output.txt to get the token and export it in environmental variable token
def parse_json():
	file_object = open('jsonoutput.txt','r')
	data=""
	for line in file_object:
	        data += line
	jsondata = json.loads(data)
	token = jsondata['access']['token']['id']
	print token
	
	file_object1 = open("fuzzload1", "r")
        i =1
	print "\n\nStarting  First(1) API FUZZ test\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api1_GET_Slash.sh', line, token])
                i +=1
        print "\n\nEnd of First(1) API FUZZ test\n\n"
	file_object1.close()
	
	file_object1 = open("fuzzload1", "r")
	i =1
	print "\n\nStarting Second(2) Fuzz API tests"
	for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
               	subprocess.call(['./api2_POST_SlashV2SlashImages.sh', line, token])
                i +=1
	print "\n\nEnd of Second(2) API FUZZ test\n\n"
	file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Third(3) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
               	subprocess.call(['./api3_GET_SlashV2SlashImages.sh', line, token])
                i +=1
        print "\n\nEnd of Third(3) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Fourth(4) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api4_GET_SlashV2SlashImagesSlashImageId.sh', line, token])
                i +=1
        print "\n\nEnd of Fourth(4) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Fifth(5) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api5_PATCH_SlashV2SlashImagesSlashImageID.sh', line, token])
                i +=1
        print "\n\nEnd of Fifth(5) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Seventh(7) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api7_PUT_SlashV2SlashImagesSlashImageIDSlashFile.sh', line, token])
                i +=1
        print "\n\nEnd of Seventh(7) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Eight(8) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api8_GET_SlashV2SlashImagesSlashImageIDSlashFile.sh', line, token])
                i +=1
        print "\n\nEnd of Eigth(8) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Ninth(9) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api9_PUT_SlashV2SlashImagesSlashImageIDSlashTagsSlashTag.sh', line, token])
                i +=1
        print "\n\nEnd of Ninth(9) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Tenth(10) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api10_DELETE_SlashV2SlashImagesSlashImageIDSlashTagsSlashTag.sh', line, token])
                i +=1
        print "\n\nEnd of Tenth(10) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Eleventh(11) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api11_POST_SlashV2SlashImagesSlashImageIDSlashMembers.sh', line, token])
                i +=1
        print "\n\nEnd of Eleventh(11) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Twelth(12) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api12_GET_SlashV2SlashImagesSlashImageIDSlashMembers.sh', line, token])
                i +=1
        print "\n\nEnd of Twelth(12) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Thirteenth(13) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api13_GET_SlashV2SlashImagesSlashImageIDSlashMembersSlashMemberID.sh', line, token])
                i +=1
        print "\n\nEnd of Thirteenth(13) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Fourteenth(14) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api14_DELETE_SlashV2SlashImagesSlashImageIDSlashMembersSlashMemberID.sh', line, token])
                i +=1
        print "\n\nEnd of Fourteenth(14) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Fifteenth(15) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api15_PUT_SlashV2SlashImagesSlashImageIDSlashMembersSlashMemberID.sh', line, token])
                i +=1
        print "\n\nEnd of Fifteenth(15) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Sixteenth(16) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api16_GET_SlashV2SlashSchemaSlashImages.sh', line, token])
                i +=1
        print "\n\nEnd of Sixteenth(16) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Seventeenth(17) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api17_GET_SlashV2SlashSchemaSlashImage.sh', line, token])
                i +=1
        print "\n\nEnd of Seventeenth(17) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Eighteenth(18) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api18_GET_SlashV2SlashSchemaSlashMembers.sh', line, token])
                i +=1
        print "\n\nEnd of Eighteenth(18) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Nineteeth(19) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                subprocess.call(['./api19_GET_SlashV2SlashSchemaSlashMember.sh', line, token])
                i +=1
        print "\n\nEnd of Nineteenth(19) API FUZZ test\n\n"
        file_object1.close()

	file_object1 = open("fuzzload1", "r")
        i =1
        print "\n\nStarting Sixth(6) Fuzz API tests\n\n"
        for line in file_object1:
                print "\nFuzz Test ", i
                line = line[:-1]
                #subprocess.call(['./api6_DELETE_SlashV2SlashImagesSlashImageID.sh', line, token])
                i +=1
        print "\n\nEnd of Sixth(6) API FUZZ test\n\n"
        file_object1.close()
get_token()
parse_json()
